### PR TITLE
resolves #16 control seed for random generators

### LINKED ISSUE #16: Add ability to control the seed for random generators
Open questions are if it should be able to be set per feature or just globally. Globally is easier and it could still have new Random instances per generator so multiple tests would not influence the generation. Using per feature / spec / generator could make it more difficult but would allow some to be reproducible. It may also be beneficial to log out the seed so on fully random runs if there was a failure it could be retried.

### PR DESCRIPTION
**Pull request by Bijnagte**
still need docs before releasing 0.5.0
cc @mariogarcia

### CODE REVIEW

**Comment by mariogarcia** [comment]
I'm afraid I won't be able to review properly this until Sunday. However I took a quick look to the code, tests passed, and so far it looks good.

**Comment by Bijnagte** [comment]
Thanks for taking all the time to review this stuff. It is helpful to have another set of eyes on it. I will have another commit with more tests and will brush up the docs. after that I think it will be time to do an actual release.

**Comment by mariogarcia** [comment]
There's just one thing I don't understand. Reading the docs...

`...For random generators it can be useful to control the seed for random generation. This will cause the same sequence of values to be generated between runs....`

Then I don't understand why running the following test I got different values for the same seed.

``` groovy
package helios

import spock.lang.Unroll
import spock.lang.Specification

import spock.genesis.Gen
import spock.genesis.transform.Iterations

@Iterations(20)
class RandomSpec extends Specification {

    static final Long SEED = 1L

    @Unroll
    void 'check sum #a + #b + #c'() {
        expect:
        COMMUTATIVE(a, b)

        and:
        ASSOCIATIVE(a, b, c)

        where: 'values are'
        a << Gen.integer(1..4).seed(SEED)
        b << Gen.integer(1..4).seed(SEED)
        c << Gen.integer(1..4).seed(SEED)
    }

    void COMMUTATIVE(a, b) {
        assert a + b == b + a
    }

    void ASSOCIATIVE(a, b, c) {
        assert a + (b + c) == (a + b) + c
    }
}

```

And the results:

```
Test    Duration    Result
check sum 1 + 1 + 1 0s  passed
check sum 1 + 1 + 1 0.001s  passed
check sum 1 + 1 + 1 0s  passed
check sum 1 + 1 + 1 0s  passed
check sum 1 + 1 + 1 0s  passed
check sum 2 + 2 + 2 0s  passed
check sum 2 + 2 + 2 0.001s  passed
check sum 2 + 2 + 2 0s  passed
check sum 2 + 2 + 2 0s  passed
check sum 2 + 2 + 2 0.022s  passed
check sum 3 + 3 + 3 0s  passed
check sum 3 + 3 + 3 0s  passed
check sum 3 + 3 + 3 0.001s  passed
check sum 3 + 3 + 3 0s  passed
check sum 3 + 3 + 3 0s  passed
check sum 4 + 4 + 4 0s  passed
check sum 4 + 4 + 4 0s  passed
check sum 4 + 4 + 4 0s  passed
check sum 4 + 4 + 4 0s  passed
check sum 4 + 4 + 4 0s  passed
```

It seems it only guarantees the same value using the same key during the same feature execution. Like if it were using the method local memory stack to store the seed and generate values from there until the end of the method execution.

Could you try to reproduce it to make sure my assumption is right ? If true, I think docs should be modify to reflect this behavior properly.

Apart from that, amazing work...as usual!

**Comment by Bijnagte** [comment]
Because all 3 generators you are using are set to have the same seed they will each produce the same the same sequence (there is no shared state between them). If you set the seed to a different value for each one they will produce different sequences:

``` groovy
package helios

import spock.lang.Unroll
import spock.lang.Specification

import spock.genesis.Gen
import spock.genesis.transform.Iterations

@Iterations(20)
class RandomSpec extends Specification {

    static final Long SEED1 = 1L
    static final Long SEED2 = 2L
    static final Long SEED3 = 3L

    @Unroll
    void 'check sum #a + #b + #c'() {
        expect:
        COMMUTATIVE(a, b)

        and:
        ASSOCIATIVE(a, b, c)

        where: 'values are'
        a << Gen.integer(1..4).seed(SEED1)
        b << Gen.integer(1..4).seed(SEED2)
        c << Gen.integer(1..4).seed(SEED3)
    }

    void COMMUTATIVE(a, b) {
        assert a + b == b + a
    }

    void ASSOCIATIVE(a, b, c) {
        assert a + (b + c) == (a + b) + c
    }
}
```

Ultimately I think that if the seed used was logged regardless of whether it was set or not would enable you to reproduce a failing test by allowing you to specify that seed.

I will see if I can update the docs to clarify more

**Comment by Bijnagte** [comment]
> It seems it only guarantees the same value using the same key during the same feature execution.

As the generator is an Iterable of random integers each iteration of the spec will call on the generator for the next value of that sequence. That sequence of random numbers and thus the values used in the unroll will always be the same sequence after the seed is set.
I updated the docs a bit. I am going to merge this and we can always do a follow on commit if it needs to be further clarified.

**Comment by mariogarcia** [comment]
Thanks for the explanation @Bijnagte For me it's clear now.

**Pull request merged**
